Điểm xuất phát: {x: 0.0, y: 0.0, yaw: 0.0}
Khu trung tâm: {x: 6.73, y: 1.38, yaw: 0.0}
Góc tây nam: {x: -7.57, y: -4.12, yaw: 0.0}
Khu vực kệ hàng: {x: 15.83, y: -1.57, yaw: 0.0}
Khu tiếp nhận: {x: 3.53, y: -6.22, yaw: 0.0}
